

# general
TITLE = 'Pooper'
AUTHORS = 'Mahen & Jono'

# screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
TOILET_WATER_BLUE = (0, 160, 255)

# toilet
TOILET_OUTLINE_WIDTH = 5
TOILET_WIDTH = SCREEN_WIDTH / 2.5
TOILET_HEIGHT = SCREEN_HEIGHT
TOILET_START_X = (SCREEN_WIDTH - TOILET_WIDTH) / 2
TOILET_START_Y = 0
