

# general
TITLE = 'Pooper'
AUTHORS = 'Mahen & Jono'

# game
MAX_LEVELS = 10
TIME_PER_LEVEL = 1  # in seconds

# screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
TOILET_WATER_BLUE = (0, 160, 255)

# toilet
TOILET_OUTLINE_WIDTH = 5
BOWL_DIFFERENCE = SCREEN_HEIGHT / 12
INNER_BOWL_WIDTH = SCREEN_WIDTH / 2.5
INNER_BOWL_HEIGHT = SCREEN_HEIGHT - (BOWL_DIFFERENCE * 2)
INNER_BOWL_START_X = (SCREEN_WIDTH - INNER_BOWL_WIDTH) / 2
INNER_BOWL_START_Y = BOWL_DIFFERENCE
OUTER_BOWL_WIDTH = INNER_BOWL_WIDTH + (BOWL_DIFFERENCE * 2)
OUTER_BOWL_HEIGHT = SCREEN_HEIGHT
OUTER_BOWL_START_X = INNER_BOWL_START_X - BOWL_DIFFERENCE
OUTER_BOWL_START_Y = 0
TOILET_TO_WATER_OFFSET = 20
