

# general
TITLE = 'Pooper'
AUTHORS = 'Mahen & Jono'

# game
MAX_WATER_LEVELS = 10
TIME_PER_LEVEL = 1  # in seconds

# screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

"""
COLOURS
"""
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
TOILET_WATER_BLUE = (0, 160, 255)

"""
TOILET SETTINGS
"""

# General
TOILET_OUTLINE_WIDTH = 5
BOWL_DIFFERENCE = SCREEN_HEIGHT / 12

# Inner bowl
INNER_BOWL_WIDTH = SCREEN_WIDTH / 2.5
INNER_BOWL_HEIGHT = SCREEN_HEIGHT - (BOWL_DIFFERENCE * 2)
INNER_BOWL_START_X = (SCREEN_WIDTH - INNER_BOWL_WIDTH) / 2
INNER_BOWL_START_Y = BOWL_DIFFERENCE

# Outer bowl
OUTER_BOWL_WIDTH = INNER_BOWL_WIDTH + (BOWL_DIFFERENCE * 2)
OUTER_BOWL_HEIGHT = SCREEN_HEIGHT
OUTER_BOWL_START_X = INNER_BOWL_START_X - BOWL_DIFFERENCE
OUTER_BOWL_START_Y = 0

# Water
WATER_SCALE_DIVISOR = 3  # increase to make the initial water level ellipse smaller
WATER_INITIAL_WIDTH = INNER_BOWL_WIDTH / WATER_SCALE_DIVISOR
WATER_INITIAL_HEIGHT = INNER_BOWL_HEIGHT / WATER_SCALE_DIVISOR
WATER_WIDTH_ADDITION_PER_LEVEL = (INNER_BOWL_WIDTH - WATER_INITIAL_WIDTH) / MAX_WATER_LEVELS
WATER_HEIGHT_ADDITION_PER_LEVEL = (INNER_BOWL_HEIGHT - WATER_INITIAL_HEIGHT) / MAX_WATER_LEVELS

# Unused
TOILET_TO_WATER_OFFSET = 20
